version: '3'

volumes:
  db_volume:

services:
  web:
    build: ./.docker/php
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - ./projdir:/var/www/html
    environment:
      VIRTUAL_HOST: bo.sample-ec.com
      TZ: Asia/Tokyo
    networks:
      - default

  db:
    build: ./.docker/mysql
    ports:
      - "13306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample_ec_db
      MYSQL_PASSWORD: password
      MYSQL_USER: username
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    networks:
      - default

  redis:
    build: ./.docker/redis
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    name: nginx-proxy
    external: true